### ISSUE TITLE
PHP 8.1 is not supported

### ISSUE THREAD

**Issue by SamuelNitsche** [Treblle/php-utils#1]
While trying to integrate the treblle-laravel sdk I noticed that the package (according to the docs) _should_ be compatible with PHP 7.4+ (or at least ^8.1 as defined in composer.json). Since this package uses readonly classes, the package _actually_ is PHP 8.2 only.

See tests: https://github.com/Treblle/php-utils/actions/runs/4924211344/jobs/8796975356

**Comment by JustSteveKing** [comment]
I have updated this and will make sure it is pulled into `treblle/treblle-laravel` shortly

**Comment by JustSteveKing** [comment]
@SamuelNitsche : https://github.com/Treblle/treblle-laravel/releases/tag/4.0.24
